services:
  wangsaff-bot:
    build: .
    container_name: wangsaff-bot
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
      - "3131:3131"
    env_file:
      - .env

